s/image=\({[^}]*}\)/source=\1/g
s/image={"mockup"}/source={"mockup"}/g
s/image={mockup}/source={mockup}/g
s/image={article\.mainImage}/source={article.mainImage}/g
s/image={item\.mainImage}/source={item.mainImage}/g
s/image={item\.image}/source={item.image}/g
s/image={featuredArticle\.mainImage}/source={featuredArticle.mainImage}/g
s/image={member\.image}/source={member.image}/g
s/image={video\.mainImage}/source={video.coverImage}/g
